FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# 安装交叉编译工具链
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    libldap2-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# 构建脚本
COPY . .

RUN make
